---
title: "BIOL 7800 - Data Science - Homework 3 - Nevyn Neal"
output:
  pdf_document: default
  html_notebook: default
---

## Question 1
```{r}
set.seed(12) # to be reproducible
A = matrix(data = runif(n = 1:500), nrow = 50, ncol = 10)
colnames(A) = paste("lake", 1:10, sep = "_")

#colMeans() solution
lake_means_1 = colMeans(A)

#for loop solution
lake_means_2 = c(rep(0,10))
for(i in 1:10){
  lake_means_2[i] = mean(A[,i])
}
lake_means_2

```

## Question 2

```{r}
x = array(1:27, dim = c(3, 3, 3))
x_2 = array(rep("null", 9), dim = c(3, 3))

for (i in 1:3){
  for (j in 1:3){
    x_2[i, j] = paste(x[i, j, 1], 
                      x[i, j, 2],
                      x[i, j, 3],
                      sep = ", ")
  }
}
x_2

# apply(X = x, MARGIN = c(1, 2), 
#        FUN = paste, collapse = ", ")
```

For some reason the collapse = ", " was not working here, only the sep = ", " argument added the comma between each character.

## Question 3
fib(n=30) = 832040 
```{r}
fib = c(rep(0, 31))
fib[1] = 0
fib[2] = 1
for (i in 3:length(fib)){
  fib[i] = fib[i-1] + fib[i-2]
}
fib[31]
```
## Question 4
```{r}
library(stringr)
top105 = readLines("http://www.textfiles.com/music/ktop100.txt")
top105 = top105[-c(64, 65)] # missing No. 54 and 55
for (i in 1:length(top105)){
  top105[i] = str_extract(top105[i], "^[:digit:]+.")
}
top105 = na.omit(top105)
top105
```
## Question 5

```{r}
for (i in 1:length(top105)){
  top105[i] = str_extract(top105[i], "[:digit:]+")
}
top105 = as.numeric(top105)
top105


top105[duplicated(top105)]

```

